import { useEffect, useMemo, useState } from 'react';
import { Building2, Users, Plus, Search, Pencil, Trash2, Award, X } from 'lucide-react';
import Fornecedores from './Fornecedores';
import DadosBancariosForm from '../components/cadastros/DadosBancariosForm';
import { carregarMunicipios } from '../components/cadastros/MunicipioInput';
import { CHIP, FAIXA, SOLIDO, TOM_MODULO, tomDe } from '../lib/cores';
import PageHeader from '../components/PageHeader';
import { FiltroPainel, FiltroLinha, GradeSeletores, CAMPO } from '../components/FiltroPainel';
import type { Tom } from '../lib/cores';

const FUNCOES: Record<string,string> = { TECNICO:'Técnico', ENCARREGADO:'Encarregado', ENGENHEIRO:'Engenheiro', ADMINISTRATIVO:'Administrativo', OUTRO:'Outro' };
// Função do funcionário: uma cor por função, igual no filtro e no cartão (lib/cores.ts).
const TOM_FUNCAO: Record<string, Tom> = { TECNICO:'blue', ENCARREGADO:'amber', ENGENHEIRO:'indigo', ADMINISTRATIVO:'slate', OUTRO:'slate' };

type Funcionario = Record<string, any> & { id: string; nome: string; qualificacoes?: any[] };
const UFS = ['AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SP','SE','TO'];
const vazio: Record<string, any> = { nome:'', cpf:'', rg:'', rg_orgao:'', data_nascimento:'', tipo_vinculo:'CLT', funcao:'', cargo:'', data_admissao:'', telefone:'', email:'', logradouro:'', numero:'', complemento:'', bairro:'', cep:'', uf:'', municipio:'', municipio_ibge:'', banco:'', agencia:'', conta:'', tipo_conta:'', pix_tipo:'CPF', pix_chave:'', forma_pagamento:'PIX', observacoes:'' };
const qVazia = { tipo:'ASO', numero:'', entidade:'', data_emissao:'', data_validade:'' };
const input = 'w-full border border-border rounded-lg p-2.5 bg-secondary/40 text-foreground focus:outline-none focus:ring-2 focus:ring-primary/30';
const label = 'block text-xs font-semibold text-muted-foreground mb-1';

export default function PessoasPrestadores({ initialTab = 'fornecedores' }: { initialTab?: 'fornecedores'|'funcionarios' }) {
  const [tab, setTab] = useState(initialTab);
  // Abas alinhadas com a margem do conteúdo (px-8): antes a barra era mais larga que a página.
  return <div><div className="px-8 pt-6"><div role="tablist" aria-label="Cadastros de pessoas" className="flex gap-2 border-b border-border">
    <button className={`px-4 py-3 text-sm font-semibold border-b-2 ${tab==='fornecedores'?'border-primary text-primary':'border-transparent text-muted-foreground'}`} onClick={()=>setTab('fornecedores')}><Building2 aria-hidden className="inline h-4 w-4 mr-2"/>Fornecedores e prestadores</button>
    <button className={`px-4 py-3 text-sm font-semibold border-b-2 ${tab==='funcionarios'?'border-primary text-primary':'border-transparent text-muted-foreground'}`} onClick={()=>setTab('funcionarios')}><Users aria-hidden className="inline h-4 w-4 mr-2"/>Funcionários LS</button>
  </div></div>{tab === 'fornecedores' ? <Fornecedores /> : <Funcionarios />}</div>;
}

function Funcionarios() {
  const [items,setItems]=useState<Funcionario[]>([]), [busca,setBusca]=useState(''), [filtroFuncao,setFiltroFuncao]=useState(''), [filtroUf,setFiltroUf]=useState('');
  const [form,setForm]=useState<Record<string,any>>(vazio), [edit,setEdit]=useState<string|null>(null), [modal,setModal]=useState(false);
  const [municipios,setMunicipios]=useState<any[]>([]), [tipos,setTipos]=useState<any[]>([]), [qualFunc,setQualFunc]=useState<Funcionario|null>(null), [q,setQ]=useState<any>(qVazia);
  const load=()=>fetch('/api/funcionarios?ativo=todos').then(r=>r.json()).then(setItems);
  useEffect(()=>{ load(); fetch('/api/qualificacoes/tipos').then(r=>r.json()).then(setTipos); },[]);
  useEffect(()=>{ if(!form.uf){setMunicipios([]);return;} carregarMunicipios(form.uf).then(setMunicipios); },[form.uf]);
  const filtrados=useMemo(()=>items.filter(f=>`${f.nome} ${f.cpf||''} ${f.cargo||''}`.toLowerCase().includes(busca.toLowerCase())&&(!filtroFuncao||(f.funcao||'')===filtroFuncao)&&(!filtroUf||f.uf===filtroUf)),[items,busca,filtroFuncao,filtroUf]);
  const ufsComGente=useMemo(()=>[...new Set(items.map(f=>f.uf).filter(Boolean))].sort(),[items]);
  const fld=(k:string,v:any)=>setForm(p=>({...p,[k]:v}));
  const abrir=(f?:Funcionario)=>{setEdit(f?.id||null);if(!f){setForm({...vazio});setModal(true);return;}const dados=Object.fromEntries(Object.keys(vazio).map(k=>[k,k.startsWith('data_')&&f[k]?String(f[k]).slice(0,10):(f[k]??'')]));if(!dados.forma_pagamento)dados.forma_pagamento=f.pix_chave?'PIX':'TED';if(!dados.pix_tipo)dados.pix_tipo='CPF';setForm(dados);setModal(true)};
  const salvar=async(e:any)=>{e.preventDefault();const r=await fetch(edit?`/api/funcionarios/${edit}`:'/api/funcionarios',{method:edit?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});if(!r.ok){alert((await r.json()).error||'Erro ao salvar');return;}setModal(false);load()};
  const remover=async(f:Funcionario)=>{if(!confirm(`Desativar ${f.nome}?`))return;await fetch(`/api/funcionarios/${f.id}`,{method:'DELETE'});load()};
  const salvarQ=async(e:any)=>{e.preventDefault();if(!qualFunc)return;const r=await fetch('/api/qualificacoes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...q,funcionario_id:qualFunc.id})});const novo=await r.json();if(!r.ok){alert(novo.error);return;}setQ(qVazia);setQualFunc(p=>p?{...p,qualificacoes:[...(p.qualificacoes||[]),novo]}:p);load()};
  const status=(x:any)=>!x.data_validade?'Sem validade':new Date(x.data_validade)<new Date()?'Vencido':`Válido até ${new Date(x.data_validade).toLocaleDateString('pt-BR',{timeZone:'UTC'})}`;
  return <div className="p-8 text-foreground"><PageHeader icone={Users} tom={TOM_MODULO.fornecedores} titulo="Funcionários LS" descricao="Cadastro pessoal, endereço IBGE, pagamento e habilitações para telecom." acoes={<button onClick={()=>abrir()} className="bg-primary text-primary-foreground hover:bg-primary/90 rounded-lg px-4 py-2.5 text-sm font-semibold flex items-center gap-2"><Plus aria-hidden className="h-4 w-4"/>Novo funcionário</button>}/>
  <FiltroPainel>
    <FiltroLinha rotulo="Buscar"><div className="flex flex-wrap items-center gap-2"><div className="relative min-w-[240px] flex-1"><Search aria-hidden className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><input className={`${CAMPO} w-full pl-9`} aria-label="Buscar funcionários" value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Buscar por nome, CPF ou cargo"/></div></div></FiltroLinha>
    <FiltroLinha rotulo="Função"><div className="flex flex-wrap items-center gap-1.5">{[["","Todas as funções"],...Object.entries(FUNCOES)].map(([id,l])=>{const n=id?items.filter(f=>f.funcao===id).length:items.length;if(id&&!n)return null;const tf=tomDe(TOM_FUNCAO,id);const at=filtroFuncao===id;return <button key={id} aria-pressed={at} onClick={()=>setFiltroFuncao(id)} className={`inline-flex h-8 items-center gap-1.5 rounded-full px-3 text-xs font-semibold leading-none ${!id?(at?"border bg-primary border-primary text-primary-foreground":"border border-border text-muted-foreground hover:text-foreground"):(at?`border border-transparent ${SOLIDO[tf]} text-background`:CHIP[tf])}`}>{l} <span className="tabular-nums opacity-60">{n}</span></button>})}</div></FiltroLinha>
    <FiltroLinha rotulo="Local"><GradeSeletores><select className={`${CAMPO} w-full`} aria-label="UF" value={filtroUf} onChange={e=>setFiltroUf(e.target.value)}><option value="">Toda UF</option>{ufsComGente.map(u=><option key={u} value={u}>{u}</option>)}</select></GradeSeletores></FiltroLinha>
  </FiltroPainel>
  <div className="mb-2 px-1 text-xs text-muted-foreground"><strong className="font-semibold text-foreground tabular-nums">{filtrados.length}</strong> de {items.length} funcionário(s)</div>
  <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-3 items-stretch">{filtrados.map(f=><div key={f.id} className={`flex h-full flex-col border border-border border-l-4 ${FAIXA[tomDe(TOM_FUNCAO,f.funcao)]} bg-card rounded-lg p-4`}><div className="flex justify-between gap-2"><div className="min-w-0"><b className="block truncate font-semibold" title={f.nome}>{f.nome}</b><div className="text-xs text-muted-foreground mt-1 flex flex-wrap items-center gap-x-3 gap-y-1">{f.funcao&&<span className={`text-[11px] font-semibold px-2 py-0.5 rounded-full ${CHIP[tomDe(TOM_FUNCAO,f.funcao)]}`}>{FUNCOES[f.funcao]||f.funcao}</span>}<span>{f.tipo_vinculo||'Vínculo não informado'}</span><span>{f.cargo||(f.funcao?FUNCOES[f.funcao]||f.funcao:'Função não informada')}</span></div></div><div className="flex shrink-0"><button aria-label={`Ver qualificações de ${f.nome}`} title="Ver qualificações" onClick={()=>setQualFunc(f)} className="p-2 rounded-md text-muted-foreground hover:text-foreground hover:bg-muted"><Award aria-hidden className="h-4 w-4"/></button><button aria-label={`Editar ${f.nome}`} title="Editar funcionário" onClick={()=>abrir(f)} className="p-2 rounded-md text-muted-foreground hover:text-foreground hover:bg-muted"><Pencil aria-hidden className="h-4 w-4"/></button><button aria-label={`Desativar ${f.nome}`} title="Desativar funcionário" onClick={()=>remover(f)} className="p-2 rounded-md text-muted-foreground hover:text-crit hover:bg-crit/10"><Trash2 aria-hidden className="h-4 w-4"/></button></div></div><div className="text-xs mt-3 flex flex-1 flex-col gap-1"><div className="flex flex-wrap gap-x-4"><span>CPF <span className={f.cpf?'font-id':'text-muted-foreground'}>{f.cpf||'—'}</span></span><span>RG <span className={f.rg?'font-id':'text-muted-foreground'}>{f.rg||'—'}</span></span></div><div>{f.municipio?`${f.municipio}/${f.uf}`:'Endereço não informado'}</div><div>{f.telefone||f.email||'Contato não informado'}</div><div className="mt-auto pt-2 border-t border-border text-muted-foreground">{f.qualificacoes?.length?`${f.qualificacoes.length} qualificação(ões)`:'Nenhuma qualificação'}</div></div></div>)}</div>
  {modal&&<Modal title={edit?'Editar funcionário':'Novo funcionário'} close={()=>setModal(false)}><form onSubmit={salvar} className="space-y-5"><Sec title="Identificação"><Grid>{[['nome','Nome completo'],['cpf','CPF'],['rg','RG'],['rg_orgao','Órgão emissor'],['data_nascimento','Nascimento','date'],['tipo_vinculo','Vínculo','select'],['cargo','Cargo'],['funcao','Função','funcao'],['data_admissao','Admissão','date'],['telefone','Telefone'],['email','E-mail']].map(([k,l,t])=><Campo key={k} k={k} l={l} t={t} value={form[k]} on={fld}/>)}</Grid></Sec><Sec title="Endereço (município validado pelo IBGE)"><Grid><Campo k="cep" l="CEP" value={form.cep} on={fld}/><Campo k="uf" l="UF" t="uf" value={form.uf} on={fld}/><label><span className={label}>Município</span><select className={input} value={form.municipio_ibge} onChange={e=>{const m=municipios.find(x=>x.codigo_ibge===e.target.value);setForm(p=>({...p,municipio_ibge:e.target.value,municipio:m?.nome||''}))}}><option value="">Selecione</option>{municipios.map(m=><option key={m.codigo_ibge} value={m.codigo_ibge}>{m.nome}</option>)}</select></label>{[['logradouro','Logradouro'],['numero','Número'],['complemento','Complemento'],['bairro','Bairro']].map(([k,l])=><Campo key={k} k={k} l={l} value={form[k]} on={fld}/>)}</Grid></Sec><DadosBancariosForm value={form} formasPermitidas={['PIX','TED','DINHEIRO']} onChange={(campo,valor)=>fld(campo,valor)}/><label><span className={label}>Observações</span><textarea className={input} value={form.observacoes} onChange={e=>fld('observacoes',e.target.value)}/></label><button className="w-full bg-primary text-primary-foreground hover:bg-primary/90 rounded-lg p-3 font-semibold">Salvar funcionário</button></form></Modal>}
  {qualFunc&&<Modal title={`Qualificações de ${qualFunc.nome}`} close={()=>setQualFunc(null)}><div className="space-y-2 mb-5">{(qualFunc.qualificacoes||[]).map(x=><div key={x.id} className="border border-border rounded-lg p-3 flex justify-between"><span><b>{tipos.find(t=>t.id===x.tipo)?.rotulo||x.tipo}</b><small className="block text-muted-foreground">{x.entidade||'Entidade não informada'}</small></span><span className={status(x)==='Vencido'?'text-crit text-xs':'text-ok text-xs'}>{status(x)}</span></div>)}</div><form onSubmit={salvarQ} className="border-t border-border pt-4"><Grid><label><span className={label}>Qualificação</span><select className={input} value={q.tipo} onChange={e=>setQ({...q,tipo:e.target.value})}>{tipos.map(t=><option key={t.id} value={t.id}>{t.rotulo}</option>)}</select></label>{[['entidade','Entidade emissora'],['numero','Nº certificado'],['data_emissao','Emissão','date'],['data_validade','Validade','date']].map(([k,l,t])=><Campo key={k} k={k} l={l} t={t} value={q[k]} on={(a:string,b:any)=>setQ((p:any)=>({...p,[a]:b}))}/>)}</Grid><button className="mt-3 w-full bg-primary text-primary-foreground hover:bg-primary/90 rounded-lg p-2 font-semibold">Adicionar qualificação</button></form></Modal>}</div>;
}
function Modal({title,close,children}:any){return <div className="fixed inset-0 z-[2000] bg-black/70 flex items-center justify-center p-4"><div className="bg-card border border-border rounded-lg shadow-2xl w-full max-w-4xl max-h-[92vh] overflow-auto p-5"><div className="flex justify-between mb-5"><h2 className="font-bold text-lg">{title}</h2><button type="button" onClick={close} aria-label="Fechar" title="Fechar" className="p-1 rounded-md text-muted-foreground hover:text-foreground"><X aria-hidden size={18}/></button></div>{children}</div></div>}
function Sec({title,children}:any){return <section className="bg-secondary/20 border border-border rounded-lg p-4"><h3 className="text-sm font-bold mb-3">{title}</h3>{children}</section>}
function Grid({children}:any){return <div className="grid grid-cols-1 md:grid-cols-2 gap-3">{children}</div>}
function Campo({k,l,t,value,on}:any){if(t==='select')return <label><span className={label}>{l}</span><select className={input} value={value} onChange={e=>on(k,e.target.value)}><option value="CLT">CLT</option><option value="PJ">Pessoa jurídica (PJ)</option><option value="AUTONOMO">Autônomo</option><option value="TERCEIRO">Terceirizado</option></select></label>;if(t==='funcao')return <label><span className={label}>{l}</span><select className={input} value={value} onChange={e=>on(k,e.target.value)}><option value="">Selecione</option><option value="TECNICO">Técnico</option><option value="ENCARREGADO">Encarregado</option><option value="ENGENHEIRO">Engenheiro</option><option value="ADMINISTRATIVO">Administrativo</option><option value="OUTRO">Outro</option></select></label>;if(t==='uf')return <label><span className={label}>{l}</span><select className={input} value={value} onChange={e=>on(k,e.target.value)}><option value="">Selecione</option>{UFS.map(x=><option key={x}>{x}</option>)}</select></label>;return <label><span className={label}>{l}</span><input required={k==='nome'} type={t||'text'} className={input} value={value||''} onChange={e=>on(k,e.target.value)}/></label>}
